app:
  build: ./keystone-demo
  ports:
   - "3000:3000"
#  volumes:
#   - ./keystone-demo:/app
  links:
   - mongo
mongo:
  image: mongo
nginx:
  build: ./nginx
  ports:
   - "80:80"
  links:
   - app